# Generated by Django 5.2.6 on 2025-09-10 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.PositiveIntegerField(verbose_name='idade'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='ear_tag_number',
            field=models.CharField(max_length=50, verbose_name='nº do brinco'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='mother_ear_tag_number',
            field=models.CharField(max_length=50, verbose_name='nº do brinco da mãe'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1, verbose_name='sexo'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.animal', verbose_name='animal'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='application_date',
            field=models.DateField(verbose_name='data de aplicação'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='second_dose',
            field=models.BooleanField(default=False, verbose_name='segunda dose'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='second_dose_date',
            field=models.DateField(blank=True, null=True, verbose_name='data da segunda dose'),
        ),
    ]
